name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.2'

    - name: Get dependencies
      run: go mod download

    - name: Build for Linux
      run: |
        GOOS=linux GOARCH=amd64 go build -o go-semi-mcp-linux-amd64 main.go
        GOOS=linux GOARCH=arm64 go build -o go-semi-mcp-linux-arm64 main.go

    - name: Build for Windows
      run: |
        GOOS=windows GOARCH=amd64 go build -o go-semi-mcp-windows-amd64.exe main.go
        GOOS=windows GOARCH=arm64 go build -o go-semi-mcp-windows-arm64.exe main.go

    - name: Build for macOS
      run: |
        GOOS=darwin GOARCH=amd64 go build -o go-semi-mcp-darwin-amd64 main.go
        GOOS=darwin GOARCH=arm64 go build -o go-semi-mcp-darwin-arm64 main.go

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          go-semi-mcp-linux-amd64
          go-semi-mcp-linux-arm64
          go-semi-mcp-windows-amd64.exe
          go-semi-mcp-windows-arm64.exe
          go-semi-mcp-darwin-amd64
          go-semi-mcp-darwin-arm64
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}